# Generated by Django 4.1.8 on 2023-04-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('idnum', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('collage', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
