# Generated by Django 4.1.8 on 2023-04-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogs_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='student_number',
            field=models.IntegerField(),
        ),
    ]
