# Generated by Django 4.1.8 on 2023-04-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_feedback_image_alter_feedback_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='fb',
        ),
    ]
