# Generated by Django 4.1.8 on 2023-04-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_feedback_fb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
